version: '3.8'
services:
  mongo:
    image: mongo:4.4.3-bionic

  koa-crud:
    image: luisangelobelmonte/koa-crud:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    links:
      - mongo
