version: 2.1

jobs:
  target: 
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/onboarding/koa-crud
    steps:
      - checkout:
          path: ~/onboarding
      - run:
          command: npm install
          name: Install dependencies
      - run:
          command: npm run test:integration
          name: Run integration test
      - run:
          command: npm run test:unit
          name: Run unit test
      - run:
          command: npm run build
          name: Run build

workflows:
  feature:
    jobs:
      - target