version: 2.1

jobs:
  target:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/onboarding/koa-crud
    steps:
      - checkout:
          path: ~/onboarding
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}
      - run:
          command: npm install
          name: Install dependencies
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  test:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/onboarding/koa-crud
    steps:
      - checkout:
          path: ~/onboarding
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}
      - run:
          command: npm run test:integration
          name: Run integration test
      - run:
          command: npm run test:unit
          name: Run unit test

  build:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/onboarding/koa-crud
    steps:
      - checkout:
          path: ~/onboarding
      - run:
          command: |
            echo ${CIRCLE_BRANCH:-br4nch} > .current-branch
            echo $CIRCLE_SHA1 > .commit-sha
          name: Save ENV variables to files for caching
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}
      - run:
          command: npm run build
          name: Run build
      - save_cache:
          key: build-{{ checksum ".commit-sha" }}-{{ checksum ".current-branch" }}
          paths:
            - build

  build_image:
    environment:
      IMAGE_NAME: luisangelobelmonte/test
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/onboarding/koa-crud
    steps:
      - checkout:
          path: ~/onboarding
      - run:
          command: |
            echo ${CIRCLE_BRANCH:-br4nch} > .current-branch
            echo $CIRCLE_SHA1 > .commit-sha
          name: Save ENV variables to files for caching
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: build-{{ checksum ".commit-sha" }}-{{ checksum ".current-branch" }}
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish image
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  CICD:
    jobs:
      - target:
          filters:
            branches:
              only:
                - /^feature\/.+$/
                - master

      - test:
          requires:
            - target
          filters:
            branches:
              only:
                - /^feature\/.+$/
                - master

      - build:
          requires:
            - target
          filters:
            branches:
              only:
                - /^feature\/.+$/
                - master

      - build_image:
          context:
            - docker-hub-secrets
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - master
