version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test: 
    working_directory: ~/koa-crud
    executor: node/default 
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test:integration
          name: Run tests
      - run:
          command: npm run build
          name: Build app

workflows:
  test_my_app:
    jobs:
      - build_and_test