name: "Feature"

on:
  push:
    branches:
      - "feature/**"

defaults:
  run:
    working-directory: ./koa-crud

jobs:
  target:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.1"

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-feature-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-feature-
            npm-
      
      - name: Install dependencies
        run: npm install

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node-modules-feature-${{ github.sha }}-${{ github.ref }}

  test:
    needs: target
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-modules-feature-${{ github.sha }}-${{ github.ref }}
      
      - name: Run integration test
        run: npm run test:integration
      
      - name: Run unit test
        run: npm run test:unit