name: "Feature"

on:
  push:
    branches:    
      - 'feature/**'

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Change directory
      run: cd ./koa-crud
    - name: Display files
      run: ll
