name: "Feature"

on:
  push:
    branches:    
      - 'feature/**'

defaults:
 run:
  working-directory: ./koa-crud

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Display files
      run: ls
